project:
  type: website
  output-dir: docs

website:
  title: "Cawthon ECR R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Intro
      - href: loops.qmd
        text: Loops


format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

