project:
  type: website
  output-dir: docs

website:
  title: "Cawthon ECR R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - intro.qmd
      - loops.qmd


format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

