project:
  type: website
  output-dir: docs

website:
  title: "Cawthon ECR R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Intro
      - href: loops.qmd
        text: Loops
      - href: bibliometric.qmd
        text: Bibliometric

format:
  html:
    theme: 
      dark: vapor
      light: flatly
    css: styles.css
    toc: true

editor: visual

